<?php
/**
 * LICENSE: Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @package   CMS\Core\Admin\FileManager
 * @author    Aram Nap <aram@bitman.nl>
 * @copyright 2015 Bitman
 * @license   http://www.apache.org/licenses/LICENSE-2.0
 */

// Import TrafficTower CMS/CodeIgniter and remove the output generated by
// TrafficTower CMS.
ob_start();

$_SERVER['REQUEST_URI'] = 'admin/file';
require '../../../../../../../../index.php';

ob_end_clean();

// Enable inside access to the instance of the TT_file controller for
// CodeIgniter integration.
$ci =& \get_instance();
$ci->set_method('get_instance', function() { return \get_instance(); });

$config = [
    // The base path of your application, with trailing directory separator.
    // This setting contains only the non-public components of the full file
    // path, webservers commonly call it the document root. Relative paths will
    // be resolved relatively to this file. Will not be sent with AJAX.
    'applicationPath' => FCPATH,

    // The path where the file manager has been installed, with trailing slash.
    // Probably the same directory as this file. Will not be sent with AJAX.
    'installationPath' => __DIR__ . '/',

    // The path where TinyMCE has been installed, with trailing slash.
    'tinymceUrl' => base_url(
        'assets/admin/grocery_crud/texteditor/tinymce4/tinymce.min.js'
    ),

    // The document path, without leading directory separator and with trailing
    // directory separator, relative to the applicationPath. It uses slashes,
    // just like an URL. The directory will be created if it doesn't exist.
    'uploadPath' => 'assets/upload/files/',

    // The path to the directory in which thumbnails for images will be stored,
    // without leading and with trailing directory separator, relative to the
    // applicationPath. It uses slashes, just like an URL. The directory will be
    // created if it doesn't exist.
    'thumbnailPath' => 'assets/upload/thumbnails/',

    // The path to the directory for storing temporary files with trailing
    // directory separator, relative to the applicationPath. The directory must
    // be publicly accessible through the web server and should only be used by
    // the file-manager to avoid overwriting unrelated files. Used to store
    // copies of images when editing them. It uses slashes, just like an URL.
    // The directory will be created if it doesn't exist. Will not be sent with
    // AJAX.
    'temporaryPath' => 'assets/admin/grocery_crud/texteditor/' .
        'tinymce4/plugins/file-manager/data/tmp/',

    // The default view type to display in the browser. Can be either "list" or
    // "thumbnails".
    'defaultFileView' => 'list',

    // The Unix permissions which will be given to uploads. Note that you
    // probably want to specify the mode as an octal number, which means they
    // should have a leading zero. They're ignored on Windows and will not be
    // sent with AJAX.
    'filePermissions' => 0664,
    'directoryPermissions' => 0775,

    // The file extensions which are allowed to be uploaded, also used to filter
    // the file type categories.
    'allowedFileExtensions' => [
        'archives' => [
            'zip',
        ],
        'documents' => [
            'doc',
            'docx',
            'htm',
            'html',
            'pdf',
            'txt',
        ],
        'images' => [
            'gif',
            'jpg',
            'jpeg',
            'png',
        ],
    ],

    // The file (MIME) types which are allowed to be uploaded. There must be at
    // least one type for every extension.
    'allowedFileTypes' => [
        'archives' => [
            'application/zip',
        ],
        'documents' => [
            'application/msword',
            'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            'text/html',
            'application/pdf',
            'application/x-bzpdf',
            'application/x-gzpdf',
            'application/x-pdf',
            'text/plain',
        ],
        'images' => [
            'image/gif',
            'image/jpeg',
            'image/png',
        ],
    ],

    // The image quality in percentage JPEG files will be saved. Don't set it
    // too high to avoid creating very large files.
    'imageQuality' => 72,

    // The CodeIgniter CSRF tokenName and hash to enable AJAX POST requests.
    'csrf' => [
        'tokenName' => $ci->get_instance()->security->get_csrf_token_name(),
        'hash' => $ci->get_instance()->security->get_csrf_hash()
    ],

    // A reference to the CodeIgniter controller. Will not be sent with AJAX.
    'ci' => $ci->get_instance()
];
